Добавлены задачи sortStrings, pick, omit
js-tasks-ru/js-20210126_mihail-sh pull request #2
Opened 2021-02-01 05:16 UTC by MikhailShakhanov

2021-02-01 09:42 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>  export function sortStrings(arr, param = 'asc') {
хорошее решение

2021-02-01 09:42 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let arrRes = arr.slice();//копируем массив, чтобы вернуть новый
`arrRes` - это `const`. Помните почему?

2021-02-01 09:43 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        let cmpRes = a.localeCompare(b,[ruCompareRule, enCompareRule]);
`cmpRes` - это тоже `const`

2021-02-01 09:43 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let arrRes = arr.slice();//копируем массив, чтобы вернуть новый
есть более коротки и современный способ копирование массива:
```
const copy = [...arr]
```

2021-02-01 09:44 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let objCopy = {};
альтернативный способ копирования объекта:
```
const copy = {...obj};
```

2021-02-01 09:45 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +      if (!fields.includes(item)) delete objCopy[item];
следует избегать использования оператора `delete` вместе с объектами, даже если предварительно они были скопированы. Подробнее обсудим на занятии

2021-02-01 09:45 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
аналогичные замечания как в `pick`

2021-02-01 09:45 UTC, dosandk approved these changes
решения принимаются, посмотрите пожалуйста комментарии :mag:

2021-02-01 10:44 UTC, MikhailShakhanov commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let arrRes = arr.slice();//копируем массив, чтобы вернуть новый
потому что это ссылка на объект массива и для понимания кода другими разработчиками она меняться не должна

2021-02-02 13:07 UTC, dosandk approved these changes

2021-02-04 14:05 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const [first,...other] = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-02-04 14:05 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return undefined;
помните что мы явно не работаем с `undefined`, достаточно просто `return`

2021-02-04 14:12 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(setUniq.values());
добавить значения в `Set` можно сразу при создании коллекции:
```
new Set([1, 2, 3])
```

2021-02-04 14:13 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(setUniq.values());
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2021-02-04 14:13 UTC, dosandk requested changes
необходимо внести правки в решение `createGetter`

2021-02-04 15:10 UTC, MikhailShakhanov commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(setUniq.values());
спред работает только с итерируемыми объектами в отличие от Array.from

2021-02-04 15:14 UTC, MikhailShakhanov commented
Поправил createGetter

2021-02-05 15:34 UTC, dosandk approved these changes

2021-02-07 16:43 UTC, MikhailShakhanov commented
Добавил ColumnChart компонент

2021-02-07 18:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  // initEventListeners () {
совет: возьмите за привычку не оставлять закомментированный код в PR-ах. 
Иногда кусок закомментированного кода оставить можно, но тогда чтобы сообщить о своих намеринях по отношению к этому коду, следует оставить TODO с пояснением

2021-02-07 18:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        value: String(Math.floor(item * scale))
здесь нет необходимости в приведении к строке

2021-02-07 19:00 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      prev += '<div style="--value: ' + current.value + '" data-tooltip="' + current.percent + '"></div>'
мы будем разбираться с этим на следующем занятии, но забегая вперед, лучше использовать `map` для построения шаблона с всего единственным вызовом `join('')` который приведет массив к строке, вместо `reduсe` с конкатенацией строк

2021-02-07 19:00 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    this.data = [...data];
good 👍

2021-02-07 19:01 UTC, dosandk approved these changes
вцелом хорошо, но не рекомендую использовать именования с нижнего подчеркивания. Конкретно в данных задачах в этом нет необходимости, а сама необходимость появляется когда мы начинаем использовать механизм наследования

2021-02-07 19:29 UTC, merged